<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title' => 'AI Tools Mastery',
                'slug' => 'ai-tools-mastery',
                'subtitle' => null,
                'tagline' => 'Work Smarter with AI — no coding required.',
                'duration' => '4 weeks',
                'hours' => '32 hrs',
                'schedule' => '3 classes a week',
                'price' => 'Contact us',
                'level' => 'Beginner',
                'tier' => 'short-term',
                'badge' => null,
                'emi' => false,
                'flagship' => false,
                'for_whom' => 'Students, teachers, shop owners, job-seekers, homemakers and government exam aspirants. If you have used WhatsApp, you can do this course.',
                'image' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'Your own Personal AI Toolkit document and three real tasks from your own work or study, completed with AI.',
                'upgrade' => 'Your full course fee is adjusted against any Professional or Career program if you enrol within 60 days.',
                'cta' => 'Enrol Now',
                'cta_note' => 'New batch starts every month',
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'How AI really works — what large language models can and cannot do',
                    'ChatGPT, Claude and Gemini — hands-on comparison and when to use which',
                    'Writing with AI — emails, applications, reports, social media posts, translation',
                    'AI for images, video and presentations — Canva AI, image generators, slide decks',
                    'AI for study and exams — notes, summaries, mock questions, doubt solving',
                    'AI for small business — invoices, catalogues, WhatsApp marketing, customer replies',
                    'Staying safe — spotting hallucinations and verifying AI output',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 1,
            ],
            [
                'title' => 'Python Programming Foundation',
                'slug' => 'python-programming-foundation',
                'subtitle' => null,
                'tagline' => 'The one skill every AI and data career starts with.',
                'duration' => '6 weeks',
                'hours' => '48 hrs',
                'schedule' => '4 classes a week',
                'price' => 'Contact us',
                'level' => 'Beginner',
                'tier' => 'short-term',
                'badge' => null,
                'emi' => false,
                'flagship' => false,
                'for_whom' => 'Freshers, BCA/B.Tech/BSc students, and anyone planning to move into AI, data analytics or machine learning.',
                'image' => 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'Two mini projects on your own GitHub profile — for example, an expense tracker and a data-cleaning tool.',
                'upgrade' => 'This course is the recommended prerequisite for our Advanced Diploma and Career Track. Enrol in either within 60 days and your full course fee is adjusted against the fee.',
                'cta' => 'Enrol Now',
                'cta_note' => null,
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'Setup, IDE, variables, data types and operators',
                    'Control flow, loops and functions',
                    'Data structures — lists, dictionaries, sets, tuples',
                    'File handling, exceptions and modules',
                    'Object-oriented programming — classes, objects, inheritance',
                    'Introduction to NumPy and Pandas',
                    'Mini project and debugging practice',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 2,
            ],
            [
                'title' => 'Generative AI & Prompt Engineering',
                'slug' => 'generative-ai-prompt-engineering',
                'subtitle' => null,
                'tagline' => 'The most in-demand AI skill of 2026 — taught properly, in person, in Lucknow.',
                'duration' => '6 weeks',
                'hours' => '48 hrs',
                'schedule' => null,
                'price' => 'Contact us',
                'level' => 'Intermediate',
                'tier' => 'short-term',
                'badge' => null,
                'emi' => false,
                'flagship' => false,
                'for_whom' => 'Working professionals, marketers, content creators, freelancers and anyone who wants to build and sell AI-powered workflows.',
                'image' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'One deployed custom AI assistant and a freelance portfolio page ready to share with clients.',
                'upgrade' => null,
                'cta' => 'Enrol Now',
                'cta_note' => 'Limited to 25 seats per batch',
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'LLM foundations — tokens, context windows, temperature, why models hallucinate',
                    'Prompt engineering — zero-shot, few-shot, chain-of-thought, role prompting, output control',
                    'Building custom GPTs and Claude Projects for specific workflows',
                    'RAG concepts — document Q&A and company knowledge bases',
                    'AI automation — Zapier, Make.com, n8n and no-code agent workflows',
                    'Monetisation — freelancing on Upwork and Fiverr, pricing AI services, winning clients',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 3,
            ],
            [
                'title' => 'AI for Business Owners & Professionals',
                'slug' => 'ai-for-business',
                'subtitle' => null,
                'tagline' => 'Run your business smarter in four weekends.',
                'duration' => '4 weeks',
                'hours' => '24 hrs',
                'schedule' => 'Weekend batches',
                'price' => 'Contact us',
                'level' => 'Beginner',
                'tier' => 'short-term',
                'badge' => 'Weekend',
                'emi' => false,
                'flagship' => false,
                'for_whom' => 'Shop owners, clinic and institute owners, agency founders, consultants, managers and senior professionals who want practical AI results without taking time off during the week.',
                'image' => 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'A working AI system for at least three recurring tasks in your business.',
                'upgrade' => null,
                'cta' => 'Reserve a Weekend Seat',
                'cta_note' => null,
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'Hands-on use of AI for customer communication, marketing content, WhatsApp and email campaigns',
                    'Documents and reports, data summaries, and day-to-day decision support',
                    'Built around your own business — bring your real tasks to class',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 4,
            ],
            [
                'title' => 'Summer / Winter Training',
                'slug' => 'summer-winter-training',
                'subtitle' => null,
                'tagline' => 'Industrial training that satisfies your college and actually teaches you something.',
                'duration' => '45 days',
                'hours' => '60 hrs',
                'schedule' => 'June–July and December–January',
                'price' => 'Contact us',
                'level' => 'Beginner',
                'tier' => 'short-term',
                'badge' => 'AKTU',
                'emi' => false,
                'flagship' => false,
                'for_whom' => 'Engineering and degree students from AKTU-affiliated colleges who need a 4–6 week industrial training certificate.',
                'image' => 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => null,
                'upgrade' => null,
                'cta' => 'Register for the Next Cycle',
                'cta_note' => null,
                'difference' => null,
                'why_it_matters' => null,
                'learning' => null,
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => ['AI/ML', 'Python', 'Data Science', 'Digital Marketing with AI'],
                'college_services' => [
                    'Official training letter on enrolment',
                    'Project report in the prescribed format',
                    'Viva preparation and support',
                    'Stamped completion certificate',
                ],
                'college_note' => 'We partner directly with training and placement departments for on-campus or in-house batches.',
                'sort_order' => 5,
            ],
            [
                'title' => 'Digital Marketing with AI — Professional',
                'slug' => 'digital-marketing-ai',
                'subtitle' => 'Professional Certificate',
                'tagline' => 'Learn marketing the way agencies practise it in 2026 — and run a live campaign with a real budget.',
                'duration' => '3 months',
                'hours' => '100 hrs',
                'schedule' => '5 classes a week',
                'price' => 'Contact us',
                'level' => 'Beginner to Intermediate',
                'tier' => 'professional',
                'badge' => null,
                'emi' => true,
                'flagship' => false,
                'for_whom' => 'Graduates, freshers, business owners and anyone targeting agency, brand or freelance marketing roles.',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => null,
                'upgrade' => null,
                'cta' => 'Enrol Now',
                'cta_note' => 'Book a Free Demo Class',
                'difference' => 'You run a live ad campaign with a real ad budget funded by the academy, and graduate with a complete case study you can show any employer or client.',
                'why_it_matters' => null,
                'learning' => [
                    'Foundations — the digital ecosystem, funnels, buyer psychology, KPIs',
                    'Websites and landing pages — WordPress, AI site builders, conversion basics',
                    'SEO with AI — keyword research, on-page and technical SEO, AI content briefs, GEO/AEO for AI search',
                    'Content and creative with AI — copywriting, image generation, short-form video, brand voice',
                    'Meta Ads — campaign structure, audiences, creative testing, Advantage+',
                    'Google Ads — Search, Performance Max, Keyword Planner, AI bidding',
                    'Social media management — organic strategy, calendars, AI scheduling tools',
                    'Email and WhatsApp marketing — automation, sequences, AI personalisation',
                    'Analytics — GA4, Search Console, Looker Studio dashboards, AI-assisted reporting',
                ],
                'career_services' => ['GitHub/portfolio setup', '1-on-1 ATS resume building', 'LinkedIn optimisation', '2 mock interviews', 'Job referrals to hiring partners', 'Lifetime batch re-attendance'],
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 6,
            ],
            [
                'title' => 'Python for Data Analytics',
                'slug' => 'python-data-analytics',
                'subtitle' => 'Professional Certificate',
                'tagline' => 'Turn raw data into decisions — the fastest route into analyst roles.',
                'duration' => '3 months',
                'hours' => '96 hrs',
                'schedule' => null,
                'price' => 'Contact us',
                'level' => 'Beginner',
                'tier' => 'professional',
                'badge' => null,
                'emi' => true,
                'flagship' => false,
                'for_whom' => 'Graduates from any stream, commerce and finance professionals, and freshers targeting data analyst, business analyst or MIS roles.',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'A portfolio of analysis projects and dashboards on GitHub, plus the full Professional career services package.',
                'upgrade' => null,
                'cta' => 'Enrol Now',
                'cta_note' => null,
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'Python for data work, Pandas and NumPy',
                    'Data cleaning and transformation',
                    'SQL for data queries',
                    'Visualisation with Matplotlib and Power BI',
                    'Descriptive statistics',
                    'Dashboards and business reporting',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 7,
            ],
            [
                'title' => 'Applied Machine Learning',
                'slug' => 'applied-machine-learning',
                'subtitle' => 'Professional Certificate',
                'tagline' => 'From data to deployed model in four months.',
                'duration' => '4 months',
                'hours' => '128 hrs',
                'schedule' => null,
                'price' => 'Contact us',
                'level' => 'Intermediate',
                'tier' => 'professional',
                'badge' => null,
                'emi' => true,
                'flagship' => false,
                'for_whom' => 'Graduates with Python fundamentals who want to build and deploy machine learning models.',
                'image' => 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => 'Python Foundation or our entrance test',
                'takeaway' => 'A deployed capstone model and a GitHub portfolio, plus the full Professional career services package.',
                'upgrade' => null,
                'cta' => 'Enrol Now',
                'cta_note' => 'Take the Free Entrance Test',
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'Math intuition — statistics, probability and linear algebra essentials, without heavy theory',
                    'Data wrangling — Pandas, NumPy, cleaning, feature engineering',
                    'Visualisation — Matplotlib, Seaborn, Power BI basics',
                    'SQL for data work',
                    'Supervised learning — regression, classification, trees, ensembles',
                    'Unsupervised learning — clustering, PCA, recommendation systems',
                    'Model evaluation, tuning and deployment with Streamlit and Flask',
                    'Capstone project',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 8,
            ],
            [
                'title' => 'Advanced Diploma in AI & Machine Learning',
                'slug' => 'advanced-diploma-ai-ml',
                'subtitle' => 'FLAGSHIP Program',
                'tagline' => 'Six months. Seven deployed projects. A portfolio that gets you interviews.',
                'duration' => '6 months',
                'hours' => '220 hrs',
                'schedule' => '5 days a week, 2 hours a day',
                'price' => 'Contact us',
                'level' => 'Beginner to Advanced',
                'tier' => 'career',
                'badge' => null,
                'emi' => true,
                'flagship' => true,
                'for_whom' => 'Freshers and career changers who want to become AI/ML engineers, data scientists or AI developers — and are ready to put in the work.',
                'image' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => '6 graded projects + 1 capstone, all deployed and live on your GitHub.',
                'upgrade' => null,
                'cta' => 'Apply Now',
                'cta_note' => 'Book a Campus Visit',
                'difference' => null,
                'why_it_matters' => null,
                'learning' => null,
                'career_services' => null,
                'included' => [
                    'Full career services package — 1-on-1 resume building, LinkedIn and GitHub optimisation, 5+ mock interviews, 20 hours of aptitude and communication training, priority job referrals',
                    'Lifetime batch re-attendance',
                    'Daily doubt-clearing lab access, 10 AM – 7 PM',
                ],
                'months' => [
                    ['month' => 'Month 1', 'title' => 'Programming & Data Foundations', 'hours' => '40 hrs', 'topics' => 'Python deep-dive, Git and GitHub, Jupyter, Pandas, NumPy, SQL'],
                    ['month' => 'Month 2', 'title' => 'Statistics & Data Analysis', 'hours' => '36 hrs', 'topics' => 'Descriptive and inferential statistics, hypothesis testing, EDA, visualisation, Power BI'],
                    ['month' => 'Month 3', 'title' => 'Core Machine Learning', 'hours' => '40 hrs', 'topics' => 'Regression, classification, decision trees, random forest, XGBoost, clustering, model evaluation, feature engineering'],
                    ['month' => 'Month 4', 'title' => 'Deep Learning', 'hours' => '40 hrs', 'topics' => 'Neural networks, TensorFlow/Keras, CNNs for computer vision, RNNs, transfer learning'],
                    ['month' => 'Month 5', 'title' => 'NLP & Generative AI', 'hours' => '40 hrs', 'topics' => 'Text processing, embeddings, transformers, LLM APIs, RAG systems, LangChain, building AI agents, fine-tuning basics'],
                    ['month' => 'Month 6', 'title' => 'Deployment, Capstone & Career', 'hours' => '24 hrs', 'topics' => 'Streamlit, FastAPI, Hugging Face Spaces, cloud basics, MLOps introduction, capstone project, portfolio build, interview preparation'],
                ],
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 9,
            ],
            [
                'title' => 'AI-Powered Digital Marketing Specialist',
                'slug' => 'ai-digital-marketing-specialist',
                'subtitle' => 'Career Program',
                'tagline' => 'Become the marketer agencies are competing to hire.',
                'duration' => '6 months',
                'hours' => '200 hrs',
                'schedule' => null,
                'price' => 'Contact us',
                'level' => 'Intermediate',
                'tier' => 'career',
                'badge' => null,
                'emi' => true,
                'flagship' => false,
                'for_whom' => 'Graduates and professionals who want a complete, career-grade marketing education with AI at its core — and placement support to match.',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => 'A multi-campaign portfolio with real results, plus the full Career-tier services package including 5+ mock interviews, aptitude and communication training, and priority placement referrals.',
                'upgrade' => null,
                'cta' => 'Apply Now',
                'cta_note' => null,
                'difference' => null,
                'why_it_matters' => null,
                'learning' => [
                    'Everything in our Digital Marketing with AI Professional program',
                    'Advanced paid media strategies',
                    'Marketing automation at scale',
                    'AI-driven content systems',
                    'Performance analytics and attribution',
                    'Client and campaign management',
                    'Multiple live campaigns across platforms',
                ],
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => null,
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 10,
            ],
            [
                'title' => 'Data Science & AI Career Track',
                'slug' => 'data-science-ai-career-track',
                'subtitle' => 'With Internship',
                'tagline' => 'Graduate with a portfolio, an internship certificate and an experience letter.',
                'duration' => '9 months',
                'hours' => '320 hrs',
                'schedule' => null,
                'price' => 'Contact us',
                'level' => 'Beginner to Advanced',
                'tier' => 'career',
                'badge' => null,
                'emi' => true,
                'flagship' => false,
                'for_whom' => 'Students who want the strongest possible start — real work experience on their CV before their first job application.',
                'image' => 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=900&q=80',
                'prerequisite' => null,
                'takeaway' => null,
                'upgrade' => null,
                'cta' => 'Apply Now',
                'cta_note' => 'Limited seats per cohort',
                'difference' => null,
                'why_it_matters' => 'Lucknow freshers compete with NCR candidates who often already have internships. An experience letter closes that gap.',
                'learning' => null,
                'career_services' => null,
                'included' => null,
                'months' => null,
                'phases' => [
                    [
                        'label' => 'Months 1–6',
                        'title' => 'Advanced Diploma in AI & ML Curriculum',
                        'desc' => 'The complete Advanced Diploma in AI & Machine Learning curriculum — programming, statistics, ML, deep learning, NLP, deployment.',
                        'items' => null,
                    ],
                    [
                        'label' => 'Months 7–9',
                        'title' => 'In-house Internship',
                        'desc' => null,
                        'items' => [
                            'Three months working on live client or academy projects under supervision',
                            'Advanced MLOps, Docker, and cloud deployment (AWS/GCP basics)',
                            'Business communication and client-handling training',
                            'Internship completion certificate and experience letter',
                            'Priority placement queue',
                        ],
                    ],
                ],
                'tracks' => null,
                'college_services' => null,
                'college_note' => null,
                'sort_order' => 11,
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(['slug' => $course['slug']], $course);
        }
    }
}
