<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class CourseController extends Controller
{
    public function index()
    {
        return Inertia::render('Courses/Index', [
            'courses' => [
                [
                    'id' => 'course_001',
                    'slug' => 'deep-learning-fundamentals',
                    'title' => 'Deep Learning Fundamentals',
                    'description' => 'Master neural networks, CNNs, RNNs, and transformers from scratch using TensorFlow and PyTorch.',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'category' => 'Deep Learning',
                    'level' => 'Intermediate',
                    'price' => 79.99,
                    'originalPrice' => 149.99,
                    'rating' => 4.9,
                    'reviewCount' => 2847,
                    'enrollmentCount' => 18420,
                    'duration' => 24,
                    'lessonCount' => 64,
                    'image' => '/images/courses/deep-learning.jpg',
                    'tags' => ['neural networks', 'tensorflow', 'pytorch', 'cnn', 'rnn'],
                ],
                [
                    'id' => 'course_002',
                    'slug' => 'nlp-with-transformers',
                    'title' => 'NLP with Transformers',
                    'description' => 'Build state-of-the-art NLP applications using BERT, GPT, and modern transformer architectures.',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'category' => 'NLP',
                    'level' => 'Advanced',
                    'price' => 99.99,
                    'originalPrice' => 199.99,
                    'rating' => 4.8,
                    'reviewCount' => 1923,
                    'enrollmentCount' => 12350,
                    'duration' => 32,
                    'lessonCount' => 78,
                    'image' => '/images/courses/nlp-transformers.jpg',
                    'tags' => ['bert', 'gpt', 'transformers', 'text classification', 'sentiment'],
                ],
                [
                    'id' => 'course_003',
                    'slug' => 'machine-learning-engineering',
                    'title' => 'Machine Learning Engineering',
                    'description' => 'End-to-end ML pipeline design, model deployment, MLOps, and production ML system architecture.',
                    'instructor' => ['name' => 'Dr. Anika Patel', 'avatar' => '/avatars/anika-patel.jpg'],
                    'category' => 'MLOps',
                    'level' => 'Intermediate',
                    'price' => 89.99,
                    'originalPrice' => 169.99,
                    'rating' => 4.9,
                    'reviewCount' => 1567,
                    'enrollmentCount' => 9870,
                    'duration' => 28,
                    'lessonCount' => 56,
                    'image' => '/images/courses/ml-engineering.jpg',
                    'tags' => ['mlops', 'deployment', 'pipelines', 'docker', 'kubernetes'],
                ],
                [
                    'id' => 'course_004',
                    'slug' => 'computer-vision-masterclass',
                    'title' => 'Computer Vision Masterclass',
                    'description' => 'Image recognition, object detection, segmentation, and video analysis using modern CV architectures.',
                    'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'],
                    'category' => 'Computer Vision',
                    'level' => 'Intermediate',
                    'price' => 84.99,
                    'originalPrice' => 159.99,
                    'rating' => 4.8,
                    'reviewCount' => 1345,
                    'enrollmentCount' => 8920,
                    'duration' => 26,
                    'lessonCount' => 52,
                    'image' => '/images/courses/computer-vision.jpg',
                    'tags' => ['opencv', 'yolo', 'resnet', 'object detection', 'segmentation'],
                ],
                [
                    'id' => 'course_005',
                    'slug' => 'generative-ai-masterclass',
                    'title' => 'Generative AI Masterclass',
                    'description' => 'LLMs, diffusion models, GANs, and creative AI. Build chatbots, image generators, and content creation tools.',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'category' => 'Generative AI',
                    'level' => 'Advanced',
                    'price' => 109.99,
                    'originalPrice' => 219.99,
                    'rating' => 4.9,
                    'reviewCount' => 2156,
                    'enrollmentCount' => 15680,
                    'duration' => 36,
                    'lessonCount' => 82,
                    'image' => '/images/courses/generative-ai.jpg',
                    'tags' => ['llm', 'diffusion', 'gan', 'chatgpt', 'stable diffusion'],
                ],
                [
                    'id' => 'course_006',
                    'slug' => 'reinforcement-learning',
                    'title' => 'Reinforcement Learning from Scratch',
                    'description' => 'Q-learning, policy gradients, actor-critic methods, and multi-agent RL for game AI and robotics.',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'category' => 'Reinforcement Learning',
                    'level' => 'Advanced',
                    'price' => 94.99,
                    'originalPrice' => 189.99,
                    'rating' => 4.7,
                    'reviewCount' => 892,
                    'enrollmentCount' => 5340,
                    'duration' => 30,
                    'lessonCount' => 68,
                    'image' => '/images/courses/reinforcement-learning.jpg',
                    'tags' => ['q-learning', 'policy gradient', 'openai gym', 'multi-agent'],
                ],
                [
                    'id' => 'course_007',
                    'slug' => 'python-for-data-science',
                    'title' => 'Python for Data Science',
                    'description' => 'Python fundamentals, NumPy, Pandas, Matplotlib, and data manipulation for AI and analytics.',
                    'instructor' => ['name' => 'Dr. Anika Patel', 'avatar' => '/avatars/anika-patel.jpg'],
                    'category' => 'Data Science',
                    'level' => 'Beginner',
                    'price' => 49.99,
                    'originalPrice' => 99.99,
                    'rating' => 4.8,
                    'reviewCount' => 4521,
                    'enrollmentCount' => 32100,
                    'duration' => 16,
                    'lessonCount' => 42,
                    'image' => '/images/courses/python-data-science.jpg',
                    'tags' => ['python', 'numpy', 'pandas', 'matplotlib', 'data analysis'],
                ],
                [
                    'id' => 'course_008',
                    'slug' => 'mlops-fundamentals',
                    'title' => 'MLOps Fundamentals',
                    'description' => 'Model versioning, CI/CD for ML, monitoring, feature stores, and production ML infrastructure.',
                    'instructor' => ['name' => 'Dr. Anika Patel', 'avatar' => '/avatars/anika-patel.jpg'],
                    'category' => 'MLOps',
                    'level' => 'Intermediate',
                    'price' => 74.99,
                    'originalPrice' => 149.99,
                    'rating' => 4.8,
                    'reviewCount' => 1123,
                    'enrollmentCount' => 7650,
                    'duration' => 20,
                    'lessonCount' => 48,
                    'image' => '/images/courses/mlops.jpg',
                    'tags' => ['mlflow', 'airflow', 'feature store', 'monitoring', 'ci/cd'],
                ],
                [
                    'id' => 'course_009',
                    'slug' => 'ai-ethics-and-governance',
                    'title' => 'AI Ethics and Governance',
                    'description' => 'Responsible AI development, bias detection, fairness metrics, and AI regulatory frameworks.',
                    'instructor' => ['name' => 'Dr. Lisa Wang', 'avatar' => '/avatars/lisa-wang.jpg'],
                    'category' => 'AI Ethics',
                    'level' => 'Beginner',
                    'price' => 59.99,
                    'originalPrice' => 119.99,
                    'rating' => 4.7,
                    'reviewCount' => 734,
                    'enrollmentCount' => 4890,
                    'duration' => 14,
                    'lessonCount' => 36,
                    'image' => '/images/courses/ai-ethics.jpg',
                    'tags' => ['fairness', 'bias', 'governance', 'regulation', 'responsible ai'],
                ],
                [
                    'id' => 'course_010',
                    'slug' => 'statistical-foundations',
                    'title' => 'Statistical Foundations for AI',
                    'description' => 'Probability, hypothesis testing, Bayesian inference, and statistical modeling for machine learning.',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'category' => 'Data Science',
                    'level' => 'Beginner',
                    'price' => 54.99,
                    'originalPrice' => 109.99,
                    'rating' => 4.6,
                    'reviewCount' => 1890,
                    'enrollmentCount' => 11200,
                    'duration' => 18,
                    'lessonCount' => 44,
                    'image' => '/images/courses/statistics.jpg',
                    'tags' => ['probability', 'bayesian', 'hypothesis testing', 'regression'],
                ],
                [
                    'id' => 'course_011',
                    'slug' => 'time-series-forecasting',
                    'title' => 'Time Series Forecasting with Deep Learning',
                    'description' => 'LSTMs, Transformers, and N-BEATS for financial forecasting, demand prediction, and anomaly detection.',
                    'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'],
                    'category' => 'Deep Learning',
                    'level' => 'Advanced',
                    'price' => 89.99,
                    'originalPrice' => 179.99,
                    'rating' => 4.8,
                    'reviewCount' => 987,
                    'enrollmentCount' => 6230,
                    'duration' => 22,
                    'lessonCount' => 50,
                    'image' => '/images/courses/time-series.jpg',
                    'tags' => ['lstm', 'transformers', 'forecasting', 'anomaly detection'],
                ],
                [
                    'id' => 'course_012',
                    'slug' => 'rag-and-llm-applications',
                    'title' => 'RAG and LLM Applications',
                    'description' => 'Build production RAG systems, fine-tune LLMs, implement vector databases, and create AI-powered applications.',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'category' => 'Generative AI',
                    'level' => 'Advanced',
                    'price' => 119.99,
                    'originalPrice' => 229.99,
                    'rating' => 4.9,
                    'reviewCount' => 1678,
                    'enrollmentCount' => 10450,
                    'duration' => 34,
                    'lessonCount' => 72,
                    'image' => '/images/courses/rag-llm.jpg',
                    'tags' => ['rag', 'langchain', 'vector database', 'fine-tuning', 'llm'],
                ],
            ],
            'categories' => [
                ['id' => 'cat_001', 'name' => 'Deep Learning', 'count' => 24],
                ['id' => 'cat_002', 'name' => 'NLP', 'count' => 18],
                ['id' => 'cat_003', 'name' => 'Computer Vision', 'count' => 15],
                ['id' => 'cat_004', 'name' => 'MLOps', 'count' => 12],
                ['id' => 'cat_005', 'name' => 'Generative AI', 'count' => 21],
                ['id' => 'cat_006', 'name' => 'Reinforcement Learning', 'count' => 9],
                ['id' => 'cat_007', 'name' => 'Data Science', 'count' => 16],
                ['id' => 'cat_008', 'name' => 'AI Ethics', 'count' => 7],
            ],
        ]);
    }

    public function show($slug)
    {
        $courses = $this->getCourseIndex();
        $course = $courses[$slug] ?? $courses['deep-learning-fundamentals'];

        return Inertia::render('Courses/Show', [
            'course' => $course,
            'curriculum' => [
                [
                    'id' => 'sec_001',
                    'title' => 'Introduction to Deep Learning',
                    'lessons' => [
                        ['id' => 'les_001', 'title' => 'What is Deep Learning?', 'type' => 'video', 'duration' => 18, 'isPreview' => true, 'content' => null],
                        ['id' => 'les_002', 'title' => 'The Neural Network Landscape', 'type' => 'article', 'duration' => 12, 'isPreview' => true, 'content' => 'Deep learning is a subset of machine learning that uses neural networks with multiple layers to progressively extract higher-level features from raw input...'],
                        ['id' => 'les_003', 'title' => 'Setting Up Your Environment', 'type' => 'video', 'duration' => 22, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_004', 'title' => 'Your First Neural Network', 'type' => 'video', 'duration' => 35, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_005', 'title' => 'Module 1 Quiz', 'type' => 'quiz', 'duration' => 15, 'isPreview' => false, 'content' => null],
                    ],
                ],
                [
                    'id' => 'sec_002',
                    'title' => 'Neural Network Architectures',
                    'lessons' => [
                        ['id' => 'les_006', 'title' => 'Perceptrons and Multi-Layer Networks', 'type' => 'video', 'duration' => 28, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_007', 'title' => 'Activation Functions Deep Dive', 'type' => 'article', 'duration' => 15, 'isPreview' => false, 'content' => 'Activation functions introduce non-linearity into neural networks, enabling them to learn complex patterns...'],
                        ['id' => 'les_008', 'title' => 'Backpropagation Explained', 'type' => 'video', 'duration' => 32, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_009', 'title' => 'Gradient Descent Optimization', 'type' => 'video', 'duration' => 25, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_010', 'title' => 'Batch Normalization and Dropout', 'type' => 'video', 'duration' => 20, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_011', 'title' => 'Build a Digit Classifier', 'type' => 'assignment', 'duration' => 45, 'isPreview' => false, 'content' => null],
                    ],
                ],
                [
                    'id' => 'sec_003',
                    'title' => 'Convolutional Neural Networks',
                    'lessons' => [
                        ['id' => 'les_012', 'title' => 'Introduction to CNNs', 'type' => 'video', 'duration' => 24, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_013', 'title' => 'Convolution and Pooling Layers', 'type' => 'video', 'duration' => 30, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_014', 'title' => 'Classic Architectures: LeNet, AlexNet, VGG', 'type' => 'article', 'duration' => 18, 'isPreview' => false, 'content' => 'The evolution of CNN architectures from LeNet-5 in 1998 to VGGNet in 2014 showed that depth matters...'],
                        ['id' => 'les_015', 'title' => 'Transfer Learning with Pre-trained Models', 'type' => 'video', 'duration' => 28, 'isPreview' => false, 'content' => null],
                        ['id' => 'les_016', 'title' => 'Image Classification Project', 'type' => 'assignment', 'duration' => 60, 'isPreview' => false, 'content' => null],
                    ],
                ],
            ],
            'instructor' => [
                'id' => 'inst_001',
                'name' => 'Dr. Sarah Mitchell',
                'avatar' => '/avatars/sarah-mitchell.jpg',
                'title' => 'AI Research Lead',
                'bio' => 'Former Google Brain researcher with 12+ years in deep learning. Published 40+ papers in top conferences. Passionate about making AI education accessible.',
                'rating' => 4.9,
                'courseCount' => 6,
                'studentCount' => 54200,
                'expertise' => ['Deep Learning', 'Generative AI', 'Neural Architecture Search'],
            ],
            'reviews' => [
                ['id' => 'rev_001', 'author' => 'Marcus Williams', 'avatar' => '/avatars/marcus.jpg', 'rating' => 5, 'date' => '2024-10-28', 'content' => 'Best deep learning course available. The progression from basics to advanced topics is perfectly paced.', 'helpful' => 142],
                ['id' => 'rev_002', 'author' => 'Elena Rodriguez', 'avatar' => '/avatars/elena.jpg', 'rating' => 5, 'date' => '2024-10-15', 'content' => 'Dr. Mitchell explains complex concepts brilliantly. The hands-on projects cement your understanding.', 'helpful' => 98],
                ['id' => 'rev_003', 'author' => 'Raj Patel', 'avatar' => '/avatars/raj.jpg', 'rating' => 4, 'date' => '2024-09-30', 'content' => 'Excellent content. Would love more coverage of graph neural networks, but overall outstanding.', 'helpful' => 67],
                ['id' => 'rev_004', 'author' => 'Sophie Laurent', 'avatar' => '/avatars/sophie.jpg', 'rating' => 5, 'date' => '2024-09-22', 'content' => 'This course helped me transition from traditional ML to deep learning. The math explanations are crystal clear.', 'helpful' => 113],
                ['id' => 'rev_005', 'author' => 'David Kim', 'avatar' => '/avatars/david.jpg', 'rating' => 5, 'date' => '2024-09-10', 'content' => 'Worth every penny. The TensorFlow and PyTorch comparison sections are incredibly valuable.', 'helpful' => 89],
                ['id' => 'rev_006', 'author' => 'Amara Okafor', 'avatar' => '/avatars/amara.jpg', 'rating' => 4, 'date' => '2024-08-28', 'content' => 'Solid course with great depth. The transformer section could use more detail, but the CNN content is world-class.', 'helpful' => 54],
            ],
            'relatedCourses' => [
                [
                    'id' => 'course_002',
                    'slug' => 'nlp-with-transformers',
                    'title' => 'NLP with Transformers',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'rating' => 4.8,
                    'reviewCount' => 1923,
                    'price' => 99.99,
                    'originalPrice' => 199.99,
                    'duration' => 32,
                    'image' => '/images/courses/nlp-transformers.jpg',
                ],
                [
                    'id' => 'course_005',
                    'slug' => 'generative-ai-masterclass',
                    'title' => 'Generative AI Masterclass',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'rating' => 4.9,
                    'reviewCount' => 2156,
                    'price' => 109.99,
                    'originalPrice' => 219.99,
                    'duration' => 36,
                    'image' => '/images/courses/generative-ai.jpg',
                ],
                [
                    'id' => 'course_011',
                    'slug' => 'time-series-forecasting',
                    'title' => 'Time Series Forecasting with Deep Learning',
                    'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'],
                    'rating' => 4.8,
                    'reviewCount' => 987,
                    'price' => 89.99,
                    'originalPrice' => 179.99,
                    'duration' => 22,
                    'image' => '/images/courses/time-series.jpg',
                ],
            ],
            'faqs' => [
                ['id' => 'faq_001', 'question' => 'What prerequisites are needed for this course?', 'answer' => 'Basic Python programming and understanding of linear algebra (matrices, vectors) are recommended. We cover the math basics in the first module.'],
                ['id' => 'faq_002', 'question' => 'How long do I have access to the course?', 'answer' => 'You get lifetime access. Once enrolled, you can revisit any lesson anytime, including future updates to the curriculum.'],
                ['id' => 'faq_003', 'question' => 'Is there a certificate upon completion?', 'answer' => 'Yes, you receive a verified certificate of completion that you can share on LinkedIn and your resume.'],
                ['id' => 'faq_004', 'question' => 'Can I get a refund if I am not satisfied?', 'answer' => 'Absolutely. We offer a 30-day money-back guarantee, no questions asked. We want you to be completely satisfied.'],
            ],
            'isEnrolled' => false,
        ]);
    }

    private function getCourseIndex()
    {
        $allCourses = $this->getCourseData();
        $indexed = [];
        foreach ($allCourses as $course) {
            $indexed[$course['slug']] = $course;
        }
        return $indexed;
    }

    private function getCourseData()
    {
        return [
            [
                'id' => 'course_001',
                'slug' => 'deep-learning-fundamentals',
                'title' => 'Deep Learning Fundamentals',
                'description' => 'Master neural networks, CNNs, RNNs, and transformers from scratch using TensorFlow and PyTorch. This comprehensive course covers everything from perceptrons to state-of-the-art architectures with hands-on projects.',
                'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                'category' => 'Deep Learning',
                'level' => 'Intermediate',
                'price' => 79.99,
                'originalPrice' => 149.99,
                'rating' => 4.9,
                'reviewCount' => 2847,
                'enrollmentCount' => 18420,
                'duration' => 24,
                'lessonCount' => 64,
                'image' => '/images/courses/deep-learning.jpg',
                'tags' => ['neural networks', 'tensorflow', 'pytorch', 'cnn', 'rnn'],
                'lastUpdated' => '2024-10-15',
                'language' => 'English',
                'captions' => ['English', 'Spanish', 'Chinese'],
            ],
        ];
    }
}
