<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class DashboardController extends Controller
{
    public function student()
    {
        return Inertia::render('Dashboard/Student', [
            'stats' => [
                ['id' => 'stat_001', 'label' => 'Enrolled Courses', 'value' => 5, 'icon' => 'book', 'change' => '+1 this month', 'changeType' => 'positive'],
                ['id' => 'stat_002', 'label' => 'Completed Courses', 'value' => 2, 'icon' => 'check', 'change' => '+1 this month', 'changeType' => 'positive'],
                ['id' => 'stat_003', 'label' => 'Learning Hours', 'value' => 47, 'icon' => 'clock', 'change' => '+12 this week', 'changeType' => 'positive'],
                ['id' => 'stat_004', 'label' => 'Certificates', 'value' => 2, 'icon' => 'award', 'change' => '+1 this month', 'changeType' => 'positive'],
            ],
            'enrollments' => [
                [
                    'id' => 'enr_001',
                    'courseId' => 'course_001',
                    'slug' => 'deep-learning-fundamentals',
                    'title' => 'Deep Learning Fundamentals',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'image' => '/images/courses/deep-learning.jpg',
                    'progress' => 65,
                    'completedLessons' => 42,
                    'totalLessons' => 64,
                    'lastAccessed' => '2024-11-12T14:30:00Z',
                    'nextLesson' => 'Recurrent Neural Networks',
                    'duration' => 24,
                ],
                [
                    'id' => 'enr_002',
                    'courseId' => 'course_005',
                    'slug' => 'generative-ai-masterclass',
                    'title' => 'Generative AI Masterclass',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'image' => '/images/courses/generative-ai.jpg',
                    'progress' => 30,
                    'completedLessons' => 25,
                    'totalLessons' => 82,
                    'lastAccessed' => '2024-11-11T10:15:00Z',
                    'nextLesson' => 'Building a Chatbot with LangChain',
                    'duration' => 36,
                ],
                [
                    'id' => 'enr_003',
                    'courseId' => 'course_007',
                    'slug' => 'python-for-data-science',
                    'title' => 'Python for Data Science',
                    'instructor' => ['name' => 'Dr. Anika Patel', 'avatar' => '/avatars/anika-patel.jpg'],
                    'image' => '/images/courses/python-data-science.jpg',
                    'progress' => 100,
                    'completedLessons' => 42,
                    'totalLessons' => 42,
                    'lastAccessed' => '2024-10-20T16:45:00Z',
                    'nextLesson' => null,
                    'duration' => 16,
                    'completedAt' => '2024-10-20',
                ],
                [
                    'id' => 'enr_004',
                    'courseId' => 'course_008',
                    'slug' => 'mlops-fundamentals',
                    'title' => 'MLOps Fundamentals',
                    'instructor' => ['name' => 'Dr. Anika Patel', 'avatar' => '/avatars/anika-patel.jpg'],
                    'image' => '/images/courses/mlops.jpg',
                    'progress' => 15,
                    'completedLessons' => 7,
                    'totalLessons' => 48,
                    'lastAccessed' => '2024-11-10T09:00:00Z',
                    'nextLesson' => 'Model Versioning with MLflow',
                    'duration' => 20,
                ],
                [
                    'id' => 'enr_005',
                    'courseId' => 'course_010',
                    'slug' => 'statistical-foundations',
                    'title' => 'Statistical Foundations for AI',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'image' => '/images/courses/statistics.jpg',
                    'progress' => 100,
                    'completedLessons' => 44,
                    'totalLessons' => 44,
                    'lastAccessed' => '2024-09-15T12:00:00Z',
                    'nextLesson' => null,
                    'duration' => 18,
                    'completedAt' => '2024-09-15',
                ],
            ],
            'certificates' => [
                [
                    'id' => 'cert_001',
                    'code' => 'CA-DL-2024-8842',
                    'courseName' => 'Deep Learning Fundamentals',
                    'completionDate' => '2024-09-15',
                    'instructorName' => 'Dr. Sarah Mitchell',
                    'grade' => 'A',
                    'score' => 94,
                ],
                [
                    'id' => 'cert_002',
                    'code' => 'CA-PDS-2024-7231',
                    'courseName' => 'Python for Data Science',
                    'completionDate' => '2024-10-20',
                    'instructorName' => 'Dr. Anika Patel',
                    'grade' => 'A+',
                    'score' => 97,
                ],
            ],
            'notifications' => [
                ['id' => 'notif_001', 'type' => 'course_update', 'message' => 'New lesson added to Deep Learning Fundamentals: "Attention Mechanisms"', 'read' => false, 'createdAt' => '2024-11-12T10:00:00Z'],
                ['id' => 'notif_002', 'type' => 'achievement', 'message' => 'Congratulations! You earned a certificate for Python for Data Science.', 'read' => false, 'createdAt' => '2024-11-11T14:30:00Z'],
                ['id' => 'notif_003', 'type' => 'reminder', 'message' => 'You have not accessed MLOps Fundamentals in 3 days. Keep up your momentum!', 'read' => false, 'createdAt' => '2024-11-10T09:00:00Z'],
                ['id' => 'notif_004', 'type' => 'community', 'message' => 'Dr. Sarah Mitchell replied to your question in Deep Learning Fundamentals.', 'read' => true, 'createdAt' => '2024-11-09T16:20:00Z'],
                ['id' => 'notif_005', 'type' => 'course_update', 'message' => 'Generative AI Masterclass updated: 3 new lessons on Vision Transformers.', 'read' => true, 'createdAt' => '2024-11-08T11:00:00Z'],
                ['id' => 'notif_006', 'type' => 'milestone', 'message' => 'You have completed 50% of Deep Learning Fundamentals. Great progress!', 'read' => true, 'createdAt' => '2024-11-07T08:45:00Z'],
                ['id' => 'notif_007', 'type' => 'promotion', 'message' => 'New course alert: "RAG and LLM Applications" - 20% off for enrolled students.', 'read' => true, 'createdAt' => '2024-11-06T10:00:00Z'],
                ['id' => 'notif_008', 'type' => 'system', 'message' => 'Your certificate for Deep Learning Fundamentals is ready to download.', 'read' => true, 'createdAt' => '2024-11-05T12:00:00Z'],
            ],
            'recommendations' => [
                [
                    'id' => 'course_012',
                    'slug' => 'rag-and-llm-applications',
                    'title' => 'RAG and LLM Applications',
                    'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'],
                    'reason' => 'Based on your interest in Deep Learning and Generative AI',
                    'price' => 119.99,
                    'rating' => 4.9,
                    'duration' => 34,
                    'image' => '/images/courses/rag-llm.jpg',
                ],
                [
                    'id' => 'course_004',
                    'slug' => 'computer-vision-masterclass',
                    'title' => 'Computer Vision Masterclass',
                    'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'],
                    'reason' => 'Popular among students who completed Python for Data Science',
                    'price' => 84.99,
                    'rating' => 4.8,
                    'duration' => 26,
                    'image' => '/images/courses/computer-vision.jpg',
                ],
                [
                    'id' => 'course_002',
                    'slug' => 'nlp-with-transformers',
                    'title' => 'NLP with Transformers',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'reason' => 'Complements your Deep Learning Fundamentals progress',
                    'price' => 99.99,
                    'rating' => 4.8,
                    'duration' => 32,
                    'image' => '/images/courses/nlp-transformers.jpg',
                ],
            ],
            'wishlist' => [
                [
                    'id' => 'course_006',
                    'slug' => 'reinforcement-learning',
                    'title' => 'Reinforcement Learning from Scratch',
                    'instructor' => ['name' => 'Prof. James Chen', 'avatar' => '/avatars/james-chen.jpg'],
                    'price' => 94.99,
                    'originalPrice' => 189.99,
                    'rating' => 4.7,
                    'image' => '/images/courses/reinforcement-learning.jpg',
                ],
                [
                    'id' => 'course_011',
                    'slug' => 'time-series-forecasting',
                    'title' => 'Time Series Forecasting with Deep Learning',
                    'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'],
                    'price' => 89.99,
                    'originalPrice' => 179.99,
                    'rating' => 4.8,
                    'image' => '/images/courses/time-series.jpg',
                ],
                [
                    'id' => 'course_009',
                    'slug' => 'ai-ethics-and-governance',
                    'title' => 'AI Ethics and Governance',
                    'instructor' => ['name' => 'Dr. Lisa Wang', 'avatar' => '/avatars/lisa-wang.jpg'],
                    'price' => 59.99,
                    'originalPrice' => 119.99,
                    'rating' => 4.7,
                    'image' => '/images/courses/ai-ethics.jpg',
                ],
            ],
            'recentActivity' => [
                ['id' => 'act_001', 'type' => 'lesson_completed', 'description' => 'Completed "Batch Normalization and Dropout" in Deep Learning Fundamentals', 'courseSlug' => 'deep-learning-fundamentals', 'createdAt' => '2024-11-12T14:30:00Z'],
                ['id' => 'act_002', 'type' => 'lesson_completed', 'description' => 'Completed "Introduction to LangChain" in Generative AI Masterclass', 'courseSlug' => 'generative-ai-masterclass', 'createdAt' => '2024-11-11T10:15:00Z'],
                ['id' => 'act_003', 'type' => 'quiz_passed', 'description' => 'Passed Module 2 Quiz with 92% in Deep Learning Fundamentals', 'courseSlug' => 'deep-learning-fundamentals', 'createdAt' => '2024-11-10T16:00:00Z'],
                ['id' => 'act_004', 'type' => 'note_created', 'description' => 'Added notes to "Activation Functions Deep Dive" in Deep Learning Fundamentals', 'courseSlug' => 'deep-learning-fundamentals', 'createdAt' => '2024-11-09T11:45:00Z'],
                ['id' => 'act_005', 'type' => 'course_started', 'description' => 'Started MLOps Fundamentals', 'courseSlug' => 'mlops-fundamentals', 'createdAt' => '2024-11-08T09:00:00Z'],
            ],
        ]);
    }

    public function instructor()
    {
        return Inertia::render('Dashboard/Instructor', [
            'stats' => [
                ['id' => 'stat_001', 'label' => 'Total Students', 'value' => 54200, 'icon' => 'users', 'change' => '+1,280 this month', 'changeType' => 'positive'],
                ['id' => 'stat_002', 'label' => 'Total Revenue', 'value' => '$284,500', 'icon' => 'dollar', 'change' => '+$32,400 this month', 'changeType' => 'positive'],
                ['id' => 'stat_003', 'label' => 'Active Courses', 'value' => 6, 'icon' => 'book', 'change' => '+1 this quarter', 'changeType' => 'positive'],
                ['id' => 'stat_004', 'label' => 'Avg. Rating', 'value' => 4.9, 'icon' => 'star', 'change' => 'Stable', 'changeType' => 'neutral'],
            ],
            'courses' => [
                [
                    'id' => 'course_001',
                    'slug' => 'deep-learning-fundamentals',
                    'title' => 'Deep Learning Fundamentals',
                    'image' => '/images/courses/deep-learning.jpg',
                    'enrollmentCount' => 18420,
                    'revenue' => '$124,800',
                    'rating' => 4.9,
                    'reviewCount' => 2847,
                    'completionRate' => 78,
                    'status' => 'published',
                    'lastUpdated' => '2024-10-15',
                ],
                [
                    'id' => 'course_005',
                    'slug' => 'generative-ai-masterclass',
                    'title' => 'Generative AI Masterclass',
                    'image' => '/images/courses/generative-ai.jpg',
                    'enrollmentCount' => 15680,
                    'revenue' => '$89,200',
                    'rating' => 4.9,
                    'reviewCount' => 2156,
                    'completionRate' => 72,
                    'status' => 'published',
                    'lastUpdated' => '2024-11-01',
                ],
                [
                    'id' => 'course_012',
                    'slug' => 'rag-and-llm-applications',
                    'title' => 'RAG and LLM Applications',
                    'image' => '/images/courses/rag-llm.jpg',
                    'enrollmentCount' => 10450,
                    'revenue' => '$58,900',
                    'rating' => 4.9,
                    'reviewCount' => 1678,
                    'completionRate' => 65,
                    'status' => 'published',
                    'lastUpdated' => '2024-11-10',
                ],
                [
                    'id' => 'course_new_001',
                    'slug' => 'advanced-prompt-engineering',
                    'title' => 'Advanced Prompt Engineering',
                    'image' => '/images/courses/prompt-engineering.jpg',
                    'enrollmentCount' => 0,
                    'revenue' => '$0',
                    'rating' => null,
                    'reviewCount' => 0,
                    'completionRate' => 0,
                    'status' => 'draft',
                    'lastUpdated' => '2024-11-12',
                ],
            ],
            'analytics' => [
                'monthlyRevenue' => [
                    ['month' => 'Jun', 'revenue' => 18200],
                    ['month' => 'Jul', 'revenue' => 21400],
                    ['month' => 'Aug', 'revenue' => 24800],
                    ['month' => 'Sep', 'revenue' => 27100],
                    ['month' => 'Oct', 'revenue' => 29600],
                    ['month' => 'Nov', 'revenue' => 32400],
                ],
                'enrollmentTrends' => [
                    ['month' => 'Jun', 'enrollments' => 1820],
                    ['month' => 'Jul', 'enrollments' => 2140],
                    ['month' => 'Aug', 'enrollments' => 2480],
                    ['month' => 'Sep', 'enrollments' => 2710],
                    ['month' => 'Oct', 'enrollments' => 2960],
                    ['month' => 'Nov', 'enrollments' => 3280],
                ],
                'topCountries' => [
                    ['country' => 'United States', 'students' => 18400, 'percentage' => 34],
                    ['country' => 'India', 'students' => 12300, 'percentage' => 23],
                    ['country' => 'United Kingdom', 'students' => 5900, 'percentage' => 11],
                    ['country' => 'Germany', 'students' => 4200, 'percentage' => 8],
                    ['country' => 'Brazil', 'students' => 3800, 'percentage' => 7],
                ],
            ],
            'questions' => [
                ['id' => 'qna_001', 'student' => ['name' => 'Marcus Williams', 'avatar' => '/avatars/marcus.jpg'], 'course' => 'Deep Learning Fundamentals', 'lesson' => 'Backpropagation Explained', 'question' => 'Why do we use the chain rule specifically for backpropagation instead of other differentiation methods?', 'status' => 'answered', 'createdAt' => '2024-11-12T09:30:00Z', 'answer' => 'The chain rule is naturally suited for neural networks because of their compositional structure. Each layer is a function of the previous layer, so the derivative of the output with respect to any weight is a product of local derivatives along the path. This is exactly what the chain rule computes efficiently.'],
                ['id' => 'qna_002', 'student' => ['name' => 'Elena Rodriguez', 'avatar' => '/avatars/elena.jpg'], 'course' => 'Generative AI Masterclass', 'lesson' => 'Diffusion Models Explained', 'question' => 'How does classifier-free guidance improve image quality in diffusion models?', 'status' => 'answered', 'createdAt' => '2024-11-11T14:15:00Z', 'answer' => 'Classifier-free guidance works by interpolating between conditional and unconditional predictions during sampling. By increasing the guidance scale, you push the model toward more strongly conditioned outputs, which improves fidelity to the text prompt at the cost of some diversity.'],
                ['id' => 'qna_003', 'student' => ['name' => 'Raj Patel', 'avatar' => '/avatars/raj.jpg'], 'course' => 'Deep Learning Fundamentals', 'lesson' => 'Transfer Learning', 'question' => 'When should I freeze the pre-trained layers versus fine-tuning them?', 'status' => 'pending', 'createdAt' => '2024-11-10T11:00:00Z', 'answer' => null],
                ['id' => 'qna_004', 'student' => ['name' => 'Sophie Laurent', 'avatar' => '/avatars/sophie.jpg'], 'course' => 'RAG and LLM Applications', 'lesson' => 'Vector Database Optimization', 'question' => 'What is the optimal chunk size for embedding technical documentation?', 'status' => 'pending', 'createdAt' => '2024-11-09T16:45:00Z', 'answer' => null],
                ['id' => 'qna_005', 'student' => ['name' => 'David Kim', 'avatar' => '/avatars/david.jpg'], 'course' => 'Generative AI Masterclass', 'lesson' => 'Building a Chatbot with LangChain', 'question' => 'How do I handle context window limitations when building a chatbot with long documents?', 'status' => 'answered', 'createdAt' => '2024-11-08T10:20:00Z', 'answer' => 'Use a sliding window approach combined with summarization. Keep recent messages in full context while summarizing older parts. Additionally, implement RAG to retrieve only relevant chunks from your document store rather than loading the entire document into context.'],
                ['id' => 'qna_006', 'student' => ['name' => 'Amara Okafor', 'avatar' => '/avatars/amara.jpg'], 'course' => 'Deep Learning Fundamentals', 'lesson' => 'Gradient Descent Optimization', 'question' => 'In what scenarios would you choose AdamW over Adam optimizer?', 'status' => 'pending', 'createdAt' => '2024-11-07T13:30:00Z', 'answer' => null],
            ],
        ]);
    }

    public function admin()
    {
        return Inertia::render('Dashboard/Admin', [
            'stats' => [
                ['id' => 'stat_001', 'label' => 'Total Users', 'value' => 125847, 'icon' => 'users', 'change' => '+3,420 this month', 'changeType' => 'positive'],
                ['id' => 'stat_002', 'label' => 'Total Revenue', 'value' => '$2,847,300', 'icon' => 'dollar', 'change' => '+$184,200 this month', 'changeType' => 'positive'],
                ['id' => 'stat_003', 'label' => 'Active Courses', 'value' => 184, 'icon' => 'book', 'change' => '+12 this month', 'changeType' => 'positive'],
                ['id' => 'stat_004', 'label' => 'Completion Rate', 'value' => '94%', 'icon' => 'chart', 'change' => '+2% this quarter', 'changeType' => 'positive'],
            ],
            'users' => [
                ['id' => 'usr_001', 'name' => 'Marcus Williams', 'email' => 'marcus.w@gmail.com', 'role' => 'student', 'joinedAt' => '2024-01-15', 'status' => 'active', 'coursesEnrolled' => 4, 'lastActive' => '2024-11-12'],
                ['id' => 'usr_002', 'name' => 'Elena Rodriguez', 'email' => 'elena.r@outlook.com', 'role' => 'student', 'joinedAt' => '2024-02-20', 'status' => 'active', 'coursesEnrolled' => 6, 'lastActive' => '2024-11-11'],
                ['id' => 'usr_003', 'name' => 'Dr. Sarah Mitchell', 'email' => 'sarah@cortexacademy.ai', 'role' => 'instructor', 'joinedAt' => '2023-06-01', 'status' => 'active', 'coursesEnrolled' => null, 'lastActive' => '2024-11-12'],
                ['id' => 'usr_004', 'name' => 'Prof. James Chen', 'email' => 'james@cortexacademy.ai', 'role' => 'instructor', 'joinedAt' => '2023-07-15', 'status' => 'active', 'coursesEnrolled' => null, 'lastActive' => '2024-11-10'],
                ['id' => 'usr_005', 'name' => 'Raj Patel', 'email' => 'raj.p@yahoo.com', 'role' => 'student', 'joinedAt' => '2024-03-10', 'status' => 'active', 'coursesEnrolled' => 3, 'lastActive' => '2024-11-09'],
                ['id' => 'usr_006', 'name' => 'Sophie Laurent', 'email' => 'sophie.l@gmail.com', 'role' => 'student', 'joinedAt' => '2024-04-05', 'status' => 'active', 'coursesEnrolled' => 5, 'lastActive' => '2024-11-08'],
                ['id' => 'usr_007', 'name' => 'David Kim', 'email' => 'david.k@proton.me', 'role' => 'student', 'joinedAt' => '2024-05-12', 'status' => 'active', 'coursesEnrolled' => 2, 'lastActive' => '2024-11-07'],
                ['id' => 'usr_008', 'name' => 'Yuki Tanaka', 'email' => 'yuki.t@icloud.com', 'role' => 'student', 'joinedAt' => '2024-06-01', 'status' => 'active', 'coursesEnrolled' => 3, 'lastActive' => '2024-11-06'],
                ['id' => 'usr_009', 'name' => 'Tomas Novak', 'email' => 'tomas.n@gmail.com', 'role' => 'student', 'joinedAt' => '2024-06-18', 'status' => 'inactive', 'coursesEnrolled' => 1, 'lastActive' => '2024-08-22'],
                ['id' => 'usr_010', 'name' => 'Amara Okafor', 'email' => 'amara.o@hotmail.com', 'role' => 'student', 'joinedAt' => '2024-07-03', 'status' => 'active', 'coursesEnrolled' => 4, 'lastActive' => '2024-11-11'],
            ],
            'pendingCourses' => [
                ['id' => 'course_p001', 'title' => 'Advanced Prompt Engineering', 'instructor' => ['name' => 'Dr. Sarah Mitchell', 'avatar' => '/avatars/sarah-mitchell.jpg'], 'submittedAt' => '2024-11-10', 'category' => 'Generative AI', 'lessonCount' => 42, 'status' => 'pending_review'],
                ['id' => 'course_p002', 'title' => 'Graph Neural Networks in Practice', 'instructor' => ['name' => 'Prof. Amara Okafor', 'avatar' => '/avatars/amara-okafor.jpg'], 'submittedAt' => '2024-11-08', 'category' => 'Deep Learning', 'lessonCount' => 36, 'status' => 'pending_review'],
                ['id' => 'course_p003', 'title' => 'AI for Healthcare Applications', 'instructor' => ['name' => 'Dr. Luis Morales', 'avatar' => '/avatars/luis-morales.jpg'], 'submittedAt' => '2024-11-05', 'category' => 'Computer Vision', 'lessonCount' => 48, 'status' => 'content_review'],
            ],
            'publishedCourses' => [
                ['id' => 'course_001', 'title' => 'Deep Learning Fundamentals', 'instructor' => 'Dr. Sarah Mitchell', 'category' => 'Deep Learning', 'enrollmentCount' => 18420, 'revenue' => '$124,800', 'rating' => 4.9, 'status' => 'published'],
                ['id' => 'course_002', 'title' => 'NLP with Transformers', 'instructor' => 'Prof. James Chen', 'category' => 'NLP', 'enrollmentCount' => 12350, 'revenue' => '$89,400', 'rating' => 4.8, 'status' => 'published'],
                ['id' => 'course_003', 'title' => 'Machine Learning Engineering', 'instructor' => 'Dr. Anika Patel', 'category' => 'MLOps', 'enrollmentCount' => 9870, 'revenue' => '$67,200', 'rating' => 4.9, 'status' => 'published'],
                ['id' => 'course_004', 'title' => 'Computer Vision Masterclass', 'instructor' => 'Dr. Luis Morales', 'category' => 'Computer Vision', 'enrollmentCount' => 8920, 'revenue' => '$58,900', 'rating' => 4.8, 'status' => 'published'],
                ['id' => 'course_005', 'title' => 'Generative AI Masterclass', 'instructor' => 'Dr. Sarah Mitchell', 'category' => 'Generative AI', 'enrollmentCount' => 15680, 'revenue' => '$112,400', 'rating' => 4.9, 'status' => 'published'],
                ['id' => 'course_006', 'title' => 'Reinforcement Learning from Scratch', 'instructor' => 'Prof. James Chen', 'category' => 'RL', 'enrollmentCount' => 5340, 'revenue' => '$34,200', 'rating' => 4.7, 'status' => 'published'],
                ['id' => 'course_007', 'title' => 'Python for Data Science', 'instructor' => 'Dr. Anika Patel', 'category' => 'Data Science', 'enrollmentCount' => 32100, 'revenue' => '$156,800', 'rating' => 4.8, 'status' => 'published'],
                ['id' => 'course_008', 'title' => 'MLOps Fundamentals', 'instructor' => 'Dr. Anika Patel', 'category' => 'MLOps', 'enrollmentCount' => 7650, 'revenue' => '$48,300', 'rating' => 4.8, 'status' => 'published'],
            ],
            'categories' => [
                ['id' => 'cat_001', 'name' => 'Deep Learning', 'courseCount' => 24, 'totalEnrollments' => 68400, 'revenue' => '$412,800'],
                ['id' => 'cat_002', 'name' => 'NLP', 'courseCount' => 18, 'totalEnrollments' => 42300, 'revenue' => '$267,400'],
                ['id' => 'cat_003', 'name' => 'Computer Vision', 'courseCount' => 15, 'totalEnrollments' => 38900, 'revenue' => '$234,600'],
                ['id' => 'cat_004', 'name' => 'MLOps', 'courseCount' => 12, 'totalEnrollments' => 28400, 'revenue' => '$178,200'],
                ['id' => 'cat_005', 'name' => 'Generative AI', 'courseCount' => 21, 'totalEnrollments' => 72100, 'revenue' => '$498,300'],
                ['id' => 'cat_006', 'name' => 'Reinforcement Learning', 'courseCount' => 9, 'totalEnrollments' => 18900, 'revenue' => '$112,400'],
                ['id' => 'cat_007', 'name' => 'Data Science', 'courseCount' => 16, 'totalEnrollments' => 52600, 'revenue' => '$312,800'],
                ['id' => 'cat_008', 'name' => 'AI Ethics', 'courseCount' => 7, 'totalEnrollments' => 14200, 'revenue' => '$78,600'],
            ],
            'orders' => [
                ['id' => 'ord_001', 'user' => 'Marcus Williams', 'course' => 'Deep Learning Fundamentals', 'amount' => 79.99, 'plan' => 'Professional', 'status' => 'completed', 'createdAt' => '2024-11-12'],
                ['id' => 'ord_002', 'user' => 'Elena Rodriguez', 'course' => 'Generative AI Masterclass', 'amount' => 109.99, 'plan' => 'Professional', 'status' => 'completed', 'createdAt' => '2024-11-11'],
                ['id' => 'ord_003', 'user' => 'Raj Patel', 'course' => 'NLP with Transformers', 'amount' => 59, 'plan' => 'Professional (Monthly)', 'status' => 'completed', 'createdAt' => '2024-11-10'],
                ['id' => 'ord_004', 'user' => 'Sophie Laurent', 'course' => 'Computer Vision Masterclass', 'amount' => 84.99, 'plan' => 'Professional', 'status' => 'completed', 'createdAt' => '2024-11-09'],
                ['id' => 'ord_005', 'user' => 'David Kim', 'course' => 'RAG and LLM Applications', 'amount' => 119.99, 'plan' => 'Enterprise', 'status' => 'completed', 'createdAt' => '2024-11-08'],
                ['id' => 'ord_006', 'user' => 'Yuki Tanaka', 'course' => 'Lifetime Access', 'amount' => 1999, 'plan' => 'Lifetime', 'status' => 'completed', 'createdAt' => '2024-11-07'],
                ['id' => 'ord_007', 'user' => 'Amara Okafor', 'course' => 'Machine Learning Engineering', 'amount' => 89.99, 'plan' => 'Professional', 'status' => 'refunded', 'createdAt' => '2024-11-06'],
                ['id' => 'ord_008', 'user' => 'Tomas Novak', 'course' => 'MLOps Fundamentals', 'amount' => 29, 'plan' => 'Explorer (Monthly)', 'status' => 'completed', 'createdAt' => '2024-11-05'],
            ],
            'reviews' => [
                ['id' => 'rev_001', 'author' => 'Marcus Williams', 'course' => 'Deep Learning Fundamentals', 'rating' => 5, 'content' => 'Best deep learning course available. Perfectly paced.', 'status' => 'approved', 'createdAt' => '2024-11-12'],
                ['id' => 'rev_002', 'author' => 'Elena Rodriguez', 'course' => 'Generative AI Masterclass', 'rating' => 5, 'content' => 'Dr. Mitchell explains complex concepts brilliantly.', 'status' => 'approved', 'createdAt' => '2024-11-11'],
                ['id' => 'rev_003', 'author' => 'Raj Patel', 'course' => 'NLP with Transformers', 'rating' => 4, 'content' => 'Excellent content. Would love more coverage of multilingual NLP.', 'status' => 'approved', 'createdAt' => '2024-11-10'],
                ['id' => 'rev_004', 'author' => 'Sophie Laurent', 'course' => 'Computer Vision Masterclass', 'rating' => 5, 'content' => 'Exactly what the industry needs. Real datasets, real problems.', 'status' => 'approved', 'createdAt' => '2024-11-09'],
                ['id' => 'rev_005', 'author' => 'David Kim', 'course' => 'RAG and LLM Applications', 'rating' => 5, 'content' => 'The RAG deployment strategies alone are worth the price.', 'status' => 'approved', 'createdAt' => '2024-11-08'],
                ['id' => 'rev_006', 'author' => 'Yuki Tanaka', 'course' => 'Python for Data Science', 'rating' => 4, 'content' => 'Great beginner course. Wish there was more pandas content.', 'status' => 'approved', 'createdAt' => '2024-11-07'],
                ['id' => 'rev_007', 'author' => 'Amara Okafor', 'course' => 'Reinforcement Learning', 'rating' => 5, 'content' => 'The multi-agent RL section is groundbreaking.', 'status' => 'approved', 'createdAt' => '2024-11-06'],
                ['id' => 'rev_008', 'author' => 'Tomas Novak', 'course' => 'MLOps Fundamentals', 'rating' => 4, 'content' => 'Solid MLOps foundation. Needs more Kubernetes-specific content.', 'status' => 'pending', 'createdAt' => '2024-11-05'],
            ],
        ]);
    }
}
