<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class HomeController extends Controller
{
    public function index()
    { 
        return Inertia::render('Home', [
            'featuredCourses' => [
                [
                    'id' => 'course_001',
                    'slug' => 'deep-learning-fundamentals',
                    'title' => 'Deep Learning Fundamentals',
                    'description' => 'Master neural networks, CNNs, RNNs, and transformers from scratch. Build real-world AI models using TensorFlow and PyTorch.',
                    'instructor' => [
                        'name' => 'Dr. Sarah Mitchell',
                        'avatar' => '/avatars/sarah-mitchell.jpg',
                    ],
                    'category' => 'Deep Learning',
                    'level' => 'Intermediate',
                    'price' => 79.99,
                    'originalPrice' => 149.99,
                    'rating' => 4.9,
                    'reviewCount' => 2847,
                    'enrollmentCount' => 18420,
                    'duration' => 24,
                    'lessonCount' => 64,
                    'image' => '/images/courses/deep-learning.jpg',
                ],
                [
                    'id' => 'course_002',
                    'slug' => 'nlp-with-transformers',
                    'title' => 'NLP with Transformers',
                    'description' => 'Build state-of-the-art NLP applications using BERT, GPT, and modern transformer architectures. Deploy to production.',
                    'instructor' => [
                        'name' => 'Prof. James Chen',
                        'avatar' => '/avatars/james-chen.jpg',
                    ],
                    'category' => 'NLP',
                    'level' => 'Advanced',
                    'price' => 99.99,
                    'originalPrice' => 199.99,
                    'rating' => 4.8,
                    'reviewCount' => 1923,
                    'enrollmentCount' => 12350,
                    'duration' => 32,
                    'lessonCount' => 78,
                    'image' => '/images/courses/nlp-transformers.jpg',
                ],
                [
                    'id' => 'course_003',
                    'slug' => 'machine-learning-engineering',
                    'title' => 'Machine Learning Engineering',
                    'description' => 'End-to-end ML pipeline design, model deployment, MLOps, and production ML system architecture.',
                    'instructor' => [
                        'name' => 'Dr. Anika Patel',
                        'avatar' => '/avatars/anika-patel.jpg',
                    ],
                    'category' => 'MLOps',
                    'level' => 'Intermediate',
                    'price' => 89.99,
                    'originalPrice' => 169.99,
                    'rating' => 4.9,
                    'reviewCount' => 1567,
                    'enrollmentCount' => 9870,
                    'duration' => 28,
                    'lessonCount' => 56,
                    'image' => '/images/courses/ml-engineering.jpg',
                ],
            ],
            'categories' => [
                ['id' => 'cat_001', 'name' => 'Deep Learning', 'icon' => 'brain', 'count' => 24, 'description' => 'Neural networks, CNNs, RNNs, and beyond'],
                ['id' => 'cat_002', 'name' => 'NLP', 'icon' => 'language', 'count' => 18, 'description' => 'Natural language processing and text AI'],
                ['id' => 'cat_003', 'name' => 'Computer Vision', 'icon' => 'eye', 'count' => 15, 'description' => 'Image recognition, object detection, and video analysis'],
                ['id' => 'cat_004', 'name' => 'MLOps', 'icon' => 'server', 'count' => 12, 'description' => 'Machine learning operations and deployment'],
                ['id' => 'cat_005', 'name' => 'Generative AI', 'icon' => 'sparkles', 'count' => 21, 'description' => 'LLMs, diffusion models, and creative AI'],
                ['id' => 'cat_006', 'name' => 'Reinforcement Learning', 'icon' => 'target', 'count' => 9, 'description' => 'Agents, rewards, and decision-making systems'],
                ['id' => 'cat_007', 'name' => 'Data Science', 'icon' => 'chart', 'count' => 16, 'description' => 'Statistics, data analysis, and visualization'],
                ['id' => 'cat_008', 'name' => 'AI Ethics', 'icon' => 'shield', 'count' => 7, 'description' => 'Responsible AI, fairness, and governance'],
            ],
            'learningPaths' => [
                [
                    'id' => 'path_001',
                    'title' => 'AI Engineer',
                    'description' => 'Go from fundamentals to deploying production AI systems. Covers Python, ML, deep learning, and MLOps.',
                    'duration' => '6 months',
                    'courseCount' => 8,
                    'difficulty' => 'Beginner to Advanced',
                    'icon' => 'code',
                    'color' => 'blue',
                ],
                [
                    'id' => 'path_002',
                    'title' => 'Data Scientist',
                    'description' => 'Master data analysis, statistical modeling, and machine learning for business intelligence.',
                    'duration' => '5 months',
                    'courseCount' => 7,
                    'difficulty' => 'Beginner to Intermediate',
                    'icon' => 'chart',
                    'color' => 'green',
                ],
                [
                    'id' => 'path_003',
                    'title' => 'ML Researcher',
                    'description' => 'Deep dive into cutting-edge research, paper implementations, and novel architectures.',
                    'duration' => '8 months',
                    'courseCount' => 10,
                    'difficulty' => 'Advanced',
                    'icon' => 'flask',
                    'color' => 'purple',
                ],
                [
                    'id' => 'path_004',
                    'title' => 'AI Product Manager',
                    'description' => 'Understand AI capabilities and limitations to lead AI-powered product development.',
                    'duration' => '3 months',
                    'courseCount' => 5,
                    'difficulty' => 'Beginner',
                    'icon' => 'lightbulb',
                    'color' => 'orange',
                ],
            ],
            'testimonials' => [
                [
                    'id' => 'test_001',
                    'name' => 'Marcus Williams',
                    'role' => 'ML Engineer at Google',
                    'avatar' => '/avatars/marcus.jpg',
                    'content' => 'AI Excellence Academy transformed my career. The deep learning course gave me the foundation to land my dream job at Google. The hands-on projects were exactly what employers look for.',
                    'rating' => 5,
                    'courseCompleted' => 'Deep Learning Fundamentals',
                ],
                [
                    'id' => 'test_002',
                    'name' => 'Elena Rodriguez',
                    'role' => 'Data Scientist at Netflix',
                    'avatar' => '/avatars/elena.jpg',
                    'content' => 'The NLP course is phenomenal. I went from basic text processing to building production chatbots in 3 months. The instructor support is unmatched.',
                    'rating' => 5,
                    'courseCompleted' => 'NLP with Transformers',
                ],
                [
                    'id' => 'test_003',
                    'name' => 'Raj Patel',
                    'role' => 'AI Lead at Stripe',
                    'avatar' => '/avatars/raj.jpg',
                    'content' => 'As a self-taught developer, AI Excellence Academy filled all my knowledge gaps. The learning paths are perfectly structured and the community is incredibly supportive.',
                    'rating' => 5,
                    'courseCompleted' => 'Machine Learning Engineering',
                ],
                [
                    'id' => 'test_004',
                    'name' => 'Sophie Laurent',
                    'role' => 'Computer Vision Engineer at Tesla',
                    'avatar' => '/avatars/sophie.jpg',
                    'content' => 'The computer vision course curriculum is exactly what the industry needs. Real datasets, real problems, real solutions. Worth every penny.',
                    'rating' => 5,
                    'courseCompleted' => 'Computer Vision Masterclass',
                ],
                [
                    'id' => 'test_005',
                    'name' => 'David Kim',
                    'role' => 'MLOps Engineer at AWS',
                    'avatar' => '/avatars/david.jpg',
                    'content' => 'I switched from traditional software engineering to MLOps thanks to AI Excellence Academy. The practical approach to model deployment saved me months of self-study.',
                    'rating' => 4,
                    'courseCompleted' => 'MLOps Fundamentals',
                ],
                [
                    'id' => 'test_006',
                    'name' => 'Amara Okafor',
                    'role' => 'Research Scientist at DeepMind',
                    'avatar' => '/avatars/amara.jpg',
                    'content' => 'Even as a PhD student, I found immense value in the advanced courses. The research-oriented content bridged the gap between academia and industry.',
                    'rating' => 5,
                    'courseCompleted' => 'Advanced Reinforcement Learning',
                ],
                [
                    'id' => 'test_007',
                    'name' => 'Tomas Novak',
                    'role' => 'AI Product Manager at Microsoft',
                    'avatar' => '/avatars/tomas.jpg',
                    'content' => 'The AI Product Manager path gave me the technical vocabulary to communicate effectively with engineering teams. Game changer for my career.',
                    'rating' => 5,
                    'courseCompleted' => 'AI Product Management',
                ],
                [
                    'id' => 'test_008',
                    'name' => 'Yuki Tanaka',
                    'role' => 'Generative AI Artist at Adobe',
                    'avatar' => '/avatars/yuki.jpg',
                    'content' => 'The Generative AI course opened up a whole new world of creative possibilities. I now build custom diffusion models for art generation.',
                    'rating' => 5,
                    'courseCompleted' => 'Generative AI Masterclass',
                ],
            ],
            'pricingTiers' => [
                [
                    'id' => 'tier_001',
                    'name' => 'Explorer',
                    'monthlyPrice' => 29,
                    'annualPrice' => 290,
                    'features' => [
                        'Access to 5 courses',
                        'Community forum access',
                        'Basic project reviews',
                        'Certificate of completion',
                        'Email support',
                    ],
                    'popular' => false,
                ],
                [
                    'id' => 'tier_002',
                    'name' => 'Professional',
                    'monthlyPrice' => 59,
                    'annualPrice' => 590,
                    'features' => [
                        'Access to all courses',
                        'Hands-on labs & projects',
                        '1-on-1 mentor sessions (2/month)',
                        'Priority project reviews',
                        'Career coaching',
                        'Job placement assistance',
                        'Downloadable resources',
                    ],
                    'popular' => true,
                ],
                [
                    'id' => 'tier_003',
                    'name' => 'Enterprise',
                    'monthlyPrice' => 99,
                    'annualPrice' => 990,
                    'features' => [
                        'Everything in Professional',
                        'Unlimited mentor sessions',
                        'Custom learning paths',
                        'Team analytics dashboard',
                        'Dedicated account manager',
                        'SLA guarantee',
                        'API access',
                        'On-site training options',
                    ],
                    'popular' => false,
                ],
                [
                    'id' => 'tier_004',
                    'name' => 'Lifetime',
                    'monthlyPrice' => null,
                    'annualPrice' => 1999,
                    'features' => [
                        'Lifetime access to all courses',
                        'All future courses included',
                        'Forever community access',
                        'Lifetime mentor sessions',
                        'Priority support',
                        'Early access to new content',
                        'Exclusive workshops',
                        'Alumni network access',
                    ],
                    'popular' => false,
                ],
            ],
        ]);
    }
}
